
[global]


disableWatchdogWarning = false
sharingMode = "off"
showWarningOnDirectExecution = true

logLevel = "debug"

[client]

caching = true
displayEnabled = true


[runner]

magicEnabled = true
installTracer = false
fixMatplotlib = true


[server]
folderWatchBlacklist = []
headless = true
liveSave = false
runOnSave = false
port = 3124
enableCORS = false
enableXsrfProtection = false

[browser]

# Internet address of the server server that the browser should connect to. Can be IP address or DNS name.
# Default: 'localhost'
serverAddress = "127.0.0.1"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = true

# Port that the browser should use to connect to the server when in liveSave mode.
# Default: whatever value is set in server.port.
serverPort = 3124
